# Site settings
title: Soul Rest In Peace
email: mizhdi@gmail.com
description: 这是我的墓志铭，往昔思念，尽数埋葬于此。
baseurl: ""
url: "mizhengdi.com"
paginate: 5
paginate_path: "blog/page:num"
owner:
  name: Retry
  desc: 慎独，自信，讲原则，可以不要脸，绝不后悔！
  avatar: http://www.gravatar.com/avatar/c83651d1bcf77550141f089aa86eae35?s=128
sass:
  style: :compressed

sns:
  - title: RSS
    href: /feed.xml
  - title: weibo
    href: http://weibo.com/208882431
  - title: email
    href: mailto:mizhdi@gmal.com
  - title: github
    href: https://github.com/mizhdi
# Build settings
markdown: kramdown

navigations: 
  - title: Home
    text: 返回首页
    href: /
  - title: Archive
    text: 所有文章
    href: /archive/
  - title: About
    text: 关于我
    href: /about/
  - title: resume
    text: 个人简历
    href: https://github.com/mizhdi/Resume
#about页图片放小尺寸