# Site settings
title: 读行 · 笃行 · 独行
email: mizhdi@gmail.com
description: 往昔思碎，尽数埋于此。
keywords: 人生旅途, 思考, 停歇, 安息, 重生
baseurl: ""
url: "mizhengdi.com"
paginate: 10
paginate_path: "blog/page:num"
sass:
  style: :compressed
gems: [jekyll-paginate, jekyll-gist]

# Build settings
markdown: kramdown

navigations:
  - title: 返回首页
    href: /
  - title: 文章分类
    href: /categories
  - title: 关于我
    href: /about
  - title: 个人简历
    href: https://github.com/mizhdi/Resume/blob/master/README.md
