# Site settings
title: 读行 · 笃行 · 独行
email: mizhdi@gmail.com
description: 往昔思碎，尽数埋于此。
keywords: 人生旅途, 思考, 停歇, 安息, 重生
baseurl: ""
url: "mizhengdi.com"
paginate: 10
paginate_path: "blog/page:num"
sass:
  style: :compressed
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers:  nil


navigations:
  - title: 返回首页
    href: /
  - title: 文章分类
    href: /categories
  - title: 我的基金
    href: /fund
  - title: 交易日志
    href: https://github.com/mizhdi/Stock-diary
  - title: 关于我
    href: /about
  - title: 个人简历
    href: https://github.com/mizhdi/Resume/blob/master/README.md
