# Site settings
title: A wonderful live
email: mizhdi@gmail.com
description: 这是我的墓志铭，往昔思念，尽数埋葬于此。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mizhdi.github.io/blog/" # the base hostname & protocol for your site
paginate: 5
paginate_path: "blog/page:num"
owner:
  name: Retry
  desc: 慎独，自信，讲原则，可以不要脸，绝不后悔！
  avatar: http://www.gravatar.com/avatar/c83651d1bcf77550141f089aa86eae35?s=128
sass:
  style: :compressed

# Build settings
markdown: kramdown

navigations: 
  - title: Home
    href: /
  - title: Archive
    href: /archive/
  - title: About
    href: /about/
  - title: resume
    href: https://github.com/mizhdi/Resume
